---
title: "Homework 5"
author: "Katie Bardsley"
date: "3/3/2021"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1

```{r}
# assign values
x <- 1.1
a <- 2.2
b <- 3.3

# a
z <- x^(a^b)
print(z)

# b
z <- (x^a)^b
print(z)

# c
z <- 3*x^3 + 2*x^2 + 1
print(z)

```

### 2

```{r}
# a
vector <- c(seq(1,8), seq(7, 1))
print(vector)

# b
vector <- rep(seq(1,5), rep(seq(1,5)))
print(vector)

# c
vector <- rep(seq(5,1), rep(seq(1,5)))
print(vector)
```

### 3

```{r}
x <- runif(1)
y <- runif(1)

r = sqrt(x^2 + y^2)
theta <- atan(y/x)

polarcoords = c(r, theta)
polarcoords

```

#### 4

```{r}
queue <- c("sheep", "fox", "owl", "ant")

# a
# serpent arrives
queue <- c(queue, "serpent")
queue

# b
# sheep enters
queue <- queue[-1]
queue

# c
# donkey cuts line
queue <- c("donkey", queue)
queue

# d
# serpent leaves
queue <- queue[-5]
queue

# e
# owl leaves
queue <- queue[-3]
queue

# f
# aphid cuts
queue <- c(queue[1:2], "aphid", queue[3])
queue

# g
# aphid position
which(queue == "aphid")

```

### 5

```{r}
k <- 1:100

# remove things divisible by 2
test <- ( k %% 2 > 0)
k <- k[test]

# remove things divisible by 3
test <- ( k %% 3 > 0)
k <- k[test]

# remove things divisible by 7
test <- ( k %% 7 > 0)
k <- k[test]

k
```

