---
title: "Homework 3"
author: "Katie Bardsley"
date: "Feb 17, 2021"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

1.
```
FIND: \h{2,}
REPLACE: ,
```
The `\h` refers to a space that is not a line break  
The `{2,}` looks for two or more consecutive spaces  
I am replacing anywhere there is two or more spaces (but not a line break), with a `,`  

___

2.
```
FIND: (\w+),\s(\w+),\s(.*)
REPLACE: \2\ \1\ \(\3\)
```
The `(\w+)` captures the first word. In this case, that is the last name. This expression appears again, in reference to the second word.   
The `,\s` looks for a comma after the first and second words, followed by a space.
The `(.*)` captures the school, capturing everything from the second space to the end of the line.  
The `\1`, `\2`, and `\3` refer to the captured segments.   
The `\ ` is a way to insert a space in the replacement.  
The `\(` and `\)` insert parentheses in the replacement.  

___

3.
```
FIND: ([^.]+.mp3)\s
REPLACE: \1\n
```
The `[^.]+` highlights a string of characters until it finds a period. Here this is the song name without the file extension. The file extension is accounted for with the `.mp3`, and this entire segment is captured with the `()`.  
The `\s` deals with the space between the song titles.  
In the replacement, the `\1` is the song title captured from above, followed by a line break `\n`.

___

4.
```
FIND: (\d+)\s([^.]+).mp3\s
REPLACE: \2_\1.mp3\n
```
The `(\d+)` highlights a string of numbers until it reaches something that isn't a number. This is how I capture the song number, which is saved in `\1`.
The `\s` refers to a space, which is followed by `([^.]+)` - which captures a sequence of characters until it reaches a period. This is the song title, which is saved as `\2`. The `.mp3\s` accounts for the file extension and the following space.  
The replace line strings together the second capture (the song title) and the first capture (the number), connected with a `_`, with the file extension `.mp3` and a new line `\n` at the end.

___

5.
```
FIND: (\w)[^,]+,(\w+),[^,]+,(\d+)
REPLACE: \1_\2,\3
```
The `(\w)` captures the first letter of the genus, which is saved in `\1`. The `[^,]+,` takes highlights the rest of the genus name and the following comma. The `(\w+)` captures the species name, which is saved in `\2`. The `,[^,]+,` highlights the next comma, the first number (by selecting everything until the next comma is reached), and the following comma, which just leaves the last number at the end. This number is captured using `(\d+)`, which saves the string of digits. This is used in the replace statement as `\3`.  
The replace statement strings together the three captures with a `_` between the first two and a `,` between the last two.  

___

6.
```
FIND: (\w)[^,]+,(\w{4})\w+,[^,]+,(\d+)
REPLACE: \1_\2,\3
```
The `(\w)` captures the first letter of the genus, which is saved in `\1`. The `[^,]+,` takes highlights the rest of the genus name and the following comma. The `(\w{4})` captures the first four letters of the species name, which is saved in `\2`. The `\w+` selects the rest of the species name. The `,[^,]+,` highlights the next comma, the first number, and the following comma, which just leaves the last number at the end. This number is captured using `(\d+)`, which saves the string of digits. This is used in the replace statement as `\3`.  
The replace statement strings together the three captures with a `_` between the first two and a `,` between the last two.  

___

7.
```
FIND: (\w{3})[^,]+,(\w{3})\w+,([^,]+),(\d+)
REPLACE: \1\2,\ \4,\ \3
```
The `(\w{3})` captures the first three letters of the genus, which is saved in `\1`. The `[^,]+,` takes highlights the rest of the genus name and the following comma. The `(\w{3})` captures the first three letters of the species name, which is saved in `\2`. The `\w+` selects the rest of the species name. The `,([^,]+),` highlights the next comma, the first number (which is captured and referenced later as `\3`), and the following comma, which just leaves the last number at the end. This number is captured using `(\d+)`, which saves the string of digits. This is used in the replace statement as `\4`.  
The replace statement strings together the four captures, putting the first two together with nothing between them `\1\2`, followed by a space `\ ` then the fourth capture `\4`, a comma and additional space `,\ `, and the third capture `\3`.  