---
title: "Homework 6"
author: "Katie Bardsley"
date: "3/10/2021"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### 1

```{r}
# Assign to the variable n_dims a single random integer between 3 and 10.
n_dims <- sample(3:10, 1)
# Create a vector of consecutive integers from 1 to n_dims2.
1:n_dims^2
# Use the sample function to randomly reshuffle these values.
(reshuffled <- sample(1:n_dims^2, length(1:n_dims^2), replace=FALSE))
# create a square matrix with these elements.
matrix <- matrix(reshuffled, nrow=n_dims)
# print out the matrix.
print(matrix)
# find a function in r to transpose the matrix.
transpose <- t(matrix)
# print it out again and note how it has changed.
print(transpose) # the rows and columns switch places
# calculate the sum and the mean of the elements in the first row and the last row.
first_sum <- sum(matrix[1,])
first_mean <- mean(matrix[1,])
last_sum <- sum(matrix[nrow(matrix),])
last_mean <- mean(matrix[nrow(matrix),])
# read about the eigen() function and use it on your matrix
eigen(matrix)
# look carefully at the elements of $values and $vectors. What kind of numbers are these?
eigen(matrix)$values  
```

These are all imaginary numbers.

```{r}
eigen(matrix)$vectors 
```

These are all imaginary numbers.

```{r}
# dig in with the typeof() function to figure out their type.
typeof(eigen(matrix)$values)  
```

These are all complex numbers.

```{r}
typeof(eigen(matrix)$vectors)  
```

These are all complex numbers.

### 2

```{r}
# Create a list with the following named elements:
# my_matrix, which is a 4 x 4 matrix filled with random uniform values
my_matrix <- matrix(runif(16), ncol=4)
print(my_matrix)
# my_logical which is a 100-element vector of TRUE or FALSE values. 
# Do this efficiently by setting up a vector of random values 
# and then applying an inequality to it.
my_logical <- runif(100) > 0.5
str(my_logical)
# my_letters, which is a 26-element vector of all the lower-case letters 
# in random order.
my_letters <- sample(letters, 26)
# create a new list, which has the element[2,2] from the matrix, 
# the second element of the logical vector, 
# and the second element of the letters vector.
new_list <- list(my_matrix[2,2], my_logical[2], my_letters[2])
print(new_list)
# use the typeof() function to confirm the underlying data types of each 
# component in this list
typeof(new_list) # list
typeof(new_list[[1]]) # double
typeof(new_list[[2]]) # logical
typeof(new_list[[3]]) # character
# combine the underlying elements from the new list into a single atomic 
# vector with the c() function. what is the data type of this vector?
new_atomic_vector <- c(new_list[[1]],new_list[[2]],new_list[[3]])
typeof(new_atomic_vector) # character
```

### 3

```{r}
# Create a data frame with two variables (= columns) and 26 cases (= rows).
# call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
my_unis <- runif(26,0,10)
print(my_unis)
# call the second variable my_letters and fill it with 26 capital letters in random order.
my_letters <- sample(LETTERS, 26)
my_data_frame <- data.frame(my_unis, my_letters)
my_data_frame
# for the first variable, use a single line of code in R to select 4 random rows and 
# replace the numerical values in those rows with NA.
my_data_frame[sample(1:26,4), 1] <- NA
print(my_data_frame)
# for the first variable, write a single line of R code to 
# identify which rows have the missing values.
which(!complete.cases(my_data_frame))
# for the second variable, sort it in alphabetical order
my_data_frame <- my_data_frame %>% arrange(my_letters, decreasing=FALSE)
my_data_frame
# calculate the column mean for the first variable.
mean(my_data_frame$my_unis, na.rm = TRUE)
```

